name: Deploy HelpContent Front

on:
  push:
    branches:
      - master   # деплой только когда обновляется master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/helpcontent.front
            git pull --no-rebase
            rm -rf node_modules .next
            npm install
            npm run build
            pm2 restart helpcontent.front --update-env
            pm2 save
